### ISSUE TITLE
개발 및 운영 서버 분리

### ISSUE THREAD

**Issue by Sim-mi-gyeong** [dnd-side-project/dnd-8th-4-backend#255]
## 💡 Issue
- [ ] 서비스 출시 및 운영에 따른 개발 서버와 분리 필요

## 📝  todo
- [ ] 개발 및 운영 서버 분리
- [ ] DB, S3 등 저장소 분리
