### ISSUE TITLE
미션 진행 기간이 지난 미션이 진행중인 미션 목록에 조회되는 이슈 수정

### ISSUE THREAD

**Issue by Sim-mi-gyeong** [dnd-side-project/dnd-8th-4-backend#262]
## 💡 Issue
- [ ] 미션 진행 기간이 지난 미션이 진행중인 미션 목록에 조회되는 이슈

## 📝  todo
- [ ] 미션 진행 기간이 지난 미션(D-day 가 - 인 경우) 은 미션 목록에서 제외 처리
- [ ] 미션 진행 기간에 따른 상태 변경 배치 확인
